version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=passwordkuat123
      - MYSQL_DATABASE=travelgo
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  php-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
      - mongo
    restart: unless-stopped

volumes:
  mysql-data:
  mongo-data:
